"""Add tg_message_id field

Revision ID: 27b682310aee
Revises: 31c1fad85799
Create Date: 2025-07-10 21:02:26.115467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b682310aee'
down_revision: Union[str, Sequence[str], None] = '31c1fad85799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_messages', sa.Column('tg_message_id', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_messages', 'tg_message_id')
    # ### end Alembic commands ###
