"""Fix composite unique constraint

Revision ID: 31c1fad85799
Revises: b376773ba227
Create Date: 2025-07-10 20:18:59.295764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c1fad85799'
down_revision: Union[str, Sequence[str], None] = 'b376773ba227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tg_messages_tg_group_id_tg_topic_id_key'), 'tg_messages', type_='unique')
    op.create_unique_constraint("tg_messages_product_id_tg_group_id_tg_topic_id_key", 'tg_messages', ['product_id', 'tg_group_id', 'tg_topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tg_messages_product_id_tg_group_id_tg_topic_id_key", 'tg_messages', type_='unique')
    op.create_unique_constraint('tg_messages_tg_group_id_tg_topic_id_key', 'tg_messages', ['tg_group_id', 'tg_topic_id'])
    # ### end Alembic commands ###
