"""Add tables

Revision ID: b376773ba227
Revises: 
Create Date: 2025-07-09 21:06:37.118850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b376773ba227'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('source_type', sa.Enum('OZON', name='products_source_type_enum', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_variants', sa.JSON(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('photos_urls', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tg_messages',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('tg_group_id', sa.BIGINT(), nullable=False),
    sa.Column('tg_topic_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_group_id', 'tg_topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_messages')
    op.drop_table('products')
    # ### end Alembic commands ###
