"""Make product_id unique

Revision ID: f1fa1210f220
Revises: 27b682310aee
Create Date: 2025-07-10 22:04:13.849797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fa1210f220'
down_revision: Union[str, Sequence[str], None] = '27b682310aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("tg_messages_product_id_key", 'tg_messages', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tg_messages_product_id_key", 'tg_messages', type_='unique')
    # ### end Alembic commands ###
