"""Make url none unique

Revision ID: f7108dfef7a3
Revises: f1fa1210f220
Create Date: 2025-07-12 23:56:36.944732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7108dfef7a3'
down_revision: Union[str, Sequence[str], None] = 'f1fa1210f220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("products_url_key", 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("products_url_key", 'products', ['url'])
    # ### end Alembic commands ###
